#!/usr/bin/perl

# Re-import user accounts into SLURM accounting system from an sacctmgr show user dump

# Input file generated by:
#  sacctmgr show user > slurmusers

open(INFILE, "<slurmusers");

while (<INFILE>) {
    $line = $_;
    chomp $line;

    ($user, $defacct, $adminlev) = split(" ", $line);

    print "Processing user " . $user . "\n";

    if ( $adminlev eq "Administ+" ) {
        system("/usr/cluster/bin/sacctmgr create user " . $user . " account=csg defaultaccount=csg qoslevel=normal defaultqos=normal adminlevel=admin");
    }

    else {
        system("/usr/cluster/bin/sacctmgr create user " . $user . " account=csg defaultaccount=csg qoslevel=normal defaultqos=normal");
    }
}

close(INFILE);
