#!/usr/bin/perl

# Re-import user accounts into Slurm accounting system from an sacctmgr show user dump

# Input file generated by:
#  sacctmgr show user > slurmusers

open(INFILE, "<slurmusers");

while (<INFILE>) {
    $line = $_;
    chomp $line;

    ($user, $defacct, $adminlev) = split(" ", $line);

    if ($adminlev eq "Administ+") {
        print "Processing admin user " . $user . " with account " . $defacct . "\n";
        system("/usr/cluster/bin/sacctmgr create user " . $user . " account=" . $defacct . " defaultaccount=" . $defacct . " qoslevel=normal defaultqos=normal adminlevel=admin");
    }

    else {
        print "Processing user " . $user . " with account " . $defacct . "\n";
        system("/usr/cluster/bin/sacctmgr create user " . $user . " account=" . $defacct . " defaultaccount=" . $defacct . " qoslevel=normal defaultqos=normal");
    }
}

close(INFILE);
