#!/bin/bash

#
# Call this from a Slurm job script to receive a report in the job log with the
# specifications of the node on which the job runs.
#

hostname=`hostname`
make=`cat /sys/devices/virtual/dmi/id/sys_vendor`
model=`cat /sys/devices/virtual/dmi/id/product_name`
cputype=`cat /proc/cpuinfo | grep "model name" | tail -1 | cut -d ":" -f 2`
corecount=`cat /proc/cpuinfo | grep "model name" | wc | tr -s " " | sed "s/^[ \t]*//" | cut -d " " -f 1`
kphysicalmem=`cat /proc/meminfo | grep MemTotal | tr -s " " | cut -d " " -f 2`
gphysicalmem=$(($kphysicalmem/1000000))

echo "*** BEGIN NODE INFORMATION ***"

echo Node name: $hostname
echo Node type: $make $model
echo CPU and clock rate: $cputype
echo Core count: $corecount
echo Physical memory $gphysicalmem GB

echo "*** END NODE INFORMATION ***"
